# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

	config.vm.box = "ubuntu/trusty64"
	config.vm.network "private_network", ip: "55.55.55.102"
	config.vm.synced_folder ".", "/home/vagrant/shared/"
	config.vm.synced_folder "../..", "/home/vagrant/sandbox/"

	config.vm.provision :shell, :path => "vm/bootstrap.sh"
	config.vm.provision :shell, run: "always", :path => "vm/init.sh"

end